void Mencryptdecryptxor(char* Message, char* key);
void MencryptCaesarCipher(char Message[],  unsigned int Key);
char* Filter(const char* Message); 
char* uplow(const char* Message, int key);
void  MFilter(char* Message);
void MremoveSpaces(char* Message);
char* toUpper(const char* Message);
void MtoUpper(char* Message);
char* toLower(const char* Message);
void MtoLower(char* Message);
void Mstrip(char* Message);
